export const emotions = [
  { name: "euphoric", core_emotion: "joy", color: "" },
  { name: "excited", core_emotion: "joy", color: "" },
  { name: "optimistic", core_emotion: "joy", color: "" },
  { name: "proud", core_emotion: "joy", color: "" },
  { name: "cheerful", core_emotion: "joy", color: "" },
  { name: "happy", core_emotion: "joy", color: "" },
  { name: "content", core_emotion: "joy", color: "" },
  { name: "peaceful", core_emotion: "joy", color: "" },

  { name: "jubilant", core_emotion: "joy", color: "" },
  { name: "elated", core_emotion: "joy", color: "" },
  { name: "zealous", core_emotion: "joy", color: "" },
  { name: "enthusiastic", core_emotion: "joy", color: "" },
  { name: "hopeful", core_emotion: "joy", color: "" },
  { name: "eager", core_emotion: "joy", color: "" },
  { name: "illustrious", core_emotion: "joy", color: "" },
  { name: "triumphant", core_emotion: "joy", color: "" },
  { name: "playful", core_emotion: "joy", color: "" },
  { name: "amused", core_emotion: "joy", color: "" },
  { name: "delighted", core_emotion: "joy", color: "" },
  { name: "jovial", core_emotion: "joy", color: "" },
  { name: "pleased", core_emotion: "joy", color: "" },
  { name: "satisfied", core_emotion: "joy", color: "" },
  { name: "serene", core_emotion: "joy", color: "" },
  { name: "tranquil", core_emotion: "joy", color: "" },

  { name: "moved", core_emotion: "surprise", color: "" },
  { name: "overcome", core_emotion: "surprise", color: "" },
  { name: "amazed", core_emotion: "surprise", color: "" },
  { name: "confused", core_emotion: "surprise", color: "" },
  { name: "stunned", core_emotion: "surprise", color: "" },

  { name: "touched", core_emotion: "surprise", color: "" },
  { name: "stimulated", core_emotion: "surprise", color: "" },
  { name: "astounded", core_emotion: "surprise", color: "" },
  { name: "speechless", core_emotion: "surprise", color: "" },
  { name: "awe_struck", core_emotion: "surprise", color: "" },
  { name: "astonished", core_emotion: "surprise", color: "" },
  { name: "perplexed", core_emotion: "surprise", color: "" },
  { name: "disillusioned", core_emotion: "surprise", color: "" },
  { name: "bewildered", core_emotion: "surprise", color: "" },
  { name: "shocked", core_emotion: "surprise", color: "" },

  { name: "gloomy", core_emotion: "sadness", color: "" },
  { name: "lonely", core_emotion: "sadness", color: "" },
  { name: "shameful", core_emotion: "sadness", color: "" },
  { name: "disappointed", core_emotion: "sadness", color: "" },
  { name: "unhappy", core_emotion: "sadness", color: "" },
  { name: "hurt", core_emotion: "sadness", color: "" },

  { name: "depressed", core_emotion: "sadness", color: "" },
  { name: "hopeless", core_emotion: "sadness", color: "" },
  { name: "neglected", core_emotion: "sadness", color: "" },
  { name: "isolated", core_emotion: "sadness", color: "" },
  { name: "guilty", core_emotion: "sadness", color: "" },
  { name: "regretful", core_emotion: "sadness", color: "" },
  { name: "displeased", core_emotion: "sadness", color: "" },
  { name: "dismayed", core_emotion: "sadness", color: "" },
  { name: "disheartened", core_emotion: "sadness", color: "" },
  { name: "miserable", core_emotion: "sadness", color: "" },
  { name: "disturbed", core_emotion: "sadness", color: "" },
  { name: "agonized", core_emotion: "sadness", color: "" },

  { name: "disgusted", core_emotion: "anger", color: "" },
  { name: "jealous", core_emotion: "anger", color: "" },
  { name: "irritable", core_emotion: "anger", color: "" },
  { name: "exasperated", core_emotion: "anger", color: "" },
  { name: "enraged", core_emotion: "anger", color: "" },

  { name: "revolted", core_emotion: "anger", color: "" },
  { name: "contemptuous", core_emotion: "anger", color: "" },
  { name: "envious", core_emotion: "anger", color: "" },
  { name: "resentful", core_emotion: "anger", color: "" },
  { name: "aggravated", core_emotion: "anger", color: "" },
  { name: "annoyed", core_emotion: "anger", color: "" },
  { name: "frustrated", core_emotion: "anger", color: "" },
  { name: "agitated", core_emotion: "anger", color: "" },
  { name: "hostile", core_emotion: "anger", color: "" },
  { name: "hateful", core_emotion: "anger", color: "" },

  { name: "horrified", core_emotion: "fear", color: "" },
  { name: "nervous", core_emotion: "fear", color: "" },
  { name: "insecure", core_emotion: "fear", color: "" },
  { name: "terrified", core_emotion: "fear", color: "" },
  { name: "scared", core_emotion: "fear", color: "" },

  { name: "dreadful", core_emotion: "fear", color: "" },
  { name: "mortified", core_emotion: "fear", color: "" },
  { name: "anxious", core_emotion: "fear", color: "" },
  { name: "worried", core_emotion: "fear", color: "" },
  { name: "inadequate", core_emotion: "fear", color: "" },
  { name: "inferior", core_emotion: "fear", color: "" },
  { name: "hysterical", core_emotion: "fear", color: "" },
  { name: "panicked", core_emotion: "fear", color: "" },
  { name: "helpless", core_emotion: "fear", color: "" },
  { name: "frightened", core_emotion: "fear", color: "" },

  { name: "grateful", core_emotion: "love", color: "" },
  { name: "sentimental", core_emotion: "love", color: "" },
  { name: "affectionate", core_emotion: "love", color: "" },
  { name: "romantic", core_emotion: "love", color: "" },
  { name: "enchanted", core_emotion: "love", color: "" },

  { name: "thankful", core_emotion: "love", color: "" },
  { name: "appreciative", core_emotion: "love", color: "" },
  { name: "nostalgic", core_emotion: "love", color: "" },
  { name: "tender", core_emotion: "love", color: "" },
  { name: "compassionate", core_emotion: "love", color: "" },
  { name: "warmhearted", core_emotion: "love", color: "" },
  { name: "enamored", core_emotion: "love", color: "" },
  { name: "passionate", core_emotion: "love", color: "" },
  { name: "rapturous", core_emotion: "love", color: "" },
  { name: "enthralled", core_emotion: "love", color: "" },
];
