import Head from "next/head";
import {
  SignOutButton,
  SignInButton,
  SignUpButton,
  useUser,
} from "@clerk/nextjs";

export default function Home() {
  const user = useUser();
  const moon_phase_report = {
    considered_date: "2-10-2017",
    moon_phase: "Balsamic Moon",
    significance:
      "The Moon now is waning and is located halfway between Last Quarter and New Moon. The seeds are moving towards maturation, while rest of the plant withers away. The energy of the plant concentrates into the seed which is preparing itself for the next cycle. In the seasonal progression, this phase represents Halloween, midway between the Fall Equinox and the Winter Solstice. The wall that separates the dead from the living, thins and ghosts walk on the plant of the living.",
    report:
      "This is a time to rest, recreate and reflect on yourself and try to reconnect with inner powerhouses of strength. It is currently not a good time to start something afresh. It is a phase where all you should do is reflect your life objectively and increase awareness of what is important to you. At this point, make your bucket list and realise your dreams and aspirations. What are the larger goals that you can you aspire to and will bring vitality and excitement into your life and make your life a little more interesting and offbeat? Just think and reflect on those aspects. Do not jump on the implementation of the listed goals.",
  };
  return (
    <>
      <Head>
        <title>Stars</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-xl">Stars</h1>
        <section className="mb-8 flex flex-col items-center">
          {!!user.user && <h2 className="">Hello {user.user.fullName}</h2>}
          {!!user.isSignedIn && (
            <SignOutButton>
              <button className="underline">Sign Out</button>
            </SignOutButton>
          )}
          {!user.isSignedIn && (
            <>
              <SignUpButton>
                <button className="underline">Create Account</button>
              </SignUpButton>
              <SignInButton>
                <button className="underline">Sign In</button>
              </SignInButton>
            </>
          )}
        </section>

        <article className="mx-8 border border-yellow-200 p-4 md:mx-36 lg:mx-72">
          <h2 className="mb-4 text-lg text-yellow-200">Sample Moon Report</h2>
          <p className="mb-2">Date: {moon_phase_report.considered_date}</p>
          <p className="mb-2">Moon Phase: {moon_phase_report.moon_phase}</p>
          <p className="mb-2">{moon_phase_report.significance} </p>
          <p className="mb-2">{moon_phase_report.report}</p>
          <button className="my-2 w-fit bg-gray-700 px-6 py-4 transition hover:bg-gray-600">
            Generate Journal Prompts (work in progress)
          </button>
        </article>
      </main>
    </>
  );
}
